{"data": {"evaluate template": {"modified_email_body": {"description": "Lots of text goes here", "template_type": "1",
                                                        "evaluatecontroller": "FOREIGN",
                                                        "email_body": "More text but different", "name": "TestString",
                                                        "email_subject": "TestString"},
                                "modified_email_subject": {"description": "Lots of text goes here",
                                                           "template_type": "1", "evaluatecontroller": "FOREIGN",
                                                           "email_body": "Lots of text goes here", "name": "TestString",
                                                           "email_subject": "Test String"},
                                "standard": {"description": "Lots of text goes here", "template_type": "1",
                                             "evaluatecontroller": "FOREIGN", "email_body": "Lots of text goes here",
                                             "name": "TestString", "email_subject": "TestString"},
                                "modified_name": {"description": "Lots of text goes here", "template_type": "1",
                                                  "evaluatecontroller": "FOREIGN",
                                                  "email_body": "Lots of text goes here", "name": "Test String",
                                                  "email_subject": "TestString"},
                                "modified_evaluatecontroller": {"description": "Lots of text goes here",
                                                                "template_type": "1", "evaluatecontroller": "FOREIGN",
                                                                "email_body": "Lots of text goes here",
                                                                "name": "TestString", "email_subject": "TestString"},
                                "modified_template_type": {"description": "Lots of text goes here",
                                                           "template_type": "3", "evaluatecontroller": "FOREIGN",
                                                           "email_body": "Lots of text goes here", "name": "TestString",
                                                           "email_subject": "TestString"},
                                "missing_evaluatecontroller": {"description": "Lots of text goes here",
                                                               "template_type": "1", "evaluatecontroller": "",
                                                               "email_body": "Lots of text goes here",
                                                               "name": "TestString", "email_subject": "TestString"},
                                "missing_email_body": {"description": "Lots of text goes here", "template_type": "1",
                                                       "evaluatecontroller": "FOREIGN", "email_body": "",
                                                       "name": "TestString", "email_subject": "TestString"},
                                "missing_name": {"description": "Lots of text goes here", "template_type": "1",
                                                 "evaluatecontroller": "FOREIGN",
                                                 "email_body": "Lots of text goes here", "name": "",
                                                 "email_subject": "TestString"},
                                "missing_email_subject": {"description": "Lots of text goes here", "template_type": "1",
                                                          "evaluatecontroller": "FOREIGN",
                                                          "email_body": "Lots of text goes here", "name": "TestString",
                                                          "email_subject": ""},
                                "missing_description": {"description": "", "template_type": "1",
                                                        "evaluatecontroller": "FOREIGN",
                                                        "email_body": "Lots of text goes here", "name": "TestString",
                                                        "email_subject": "TestString"},
                                "modified_description": {"description": "More text but different", "template_type": "1",
                                                         "evaluatecontroller": "FOREIGN",
                                                         "email_body": "Lots of text goes here", "name": "TestString",
                                                         "email_subject": "TestString"},
                                "missing_template_type": {"description": "Lots of text goes here", "template_type": "",
                                                          "evaluatecontroller": "FOREIGN",
                                                          "email_body": "Lots of text goes here", "name": "TestString",
                                                          "email_subject": "TestString"}}, "evaluate target profile": {
    "modified_delivery_status": {"evaluateresult": "FOREIGN", "target": "FOREIGN", "delivery_status": "3",
                                 "token": "TestString", "controller": "FOREIGN"},
    "missing_token": {"evaluateresult": "FOREIGN", "target": "FOREIGN", "delivery_status": "1", "token": "",
                      "controller": "FOREIGN"},
    "standard": {"evaluateresult": "FOREIGN", "target": "FOREIGN", "delivery_status": "1", "token": "TestString",
                 "controller": "FOREIGN"},
    "modified_target": {"evaluateresult": "FOREIGN", "target": "FOREIGN", "delivery_status": "1", "token": "TestString",
                        "controller": "FOREIGN"},
    "missing_delivery_status": {"evaluateresult": "FOREIGN", "target": "FOREIGN", "delivery_status": "",
                                "token": "TestString", "controller": "FOREIGN"},
    "missing_target": {"evaluateresult": "FOREIGN", "target": "", "delivery_status": "1", "token": "TestString",
                       "controller": "FOREIGN"},
    "modified_controller": {"evaluateresult": "FOREIGN", "target": "FOREIGN", "delivery_status": "1",
                            "token": "TestString", "controller": "FOREIGN"},
    "modified_evaluateresult": {"evaluateresult": "FOREIGN", "target": "FOREIGN", "delivery_status": "1",
                                "token": "TestString", "controller": "FOREIGN"},
    "modified_token": {"evaluateresult": "FOREIGN", "target": "FOREIGN", "delivery_status": "1", "token": "Test String",
                       "controller": "FOREIGN"},
    "missing_controller": {"evaluateresult": "FOREIGN", "target": "FOREIGN", "delivery_status": "1",
                           "token": "TestString", "controller": ""},
    "missing_evaluateresult": {"evaluateresult": "", "target": "FOREIGN", "delivery_status": "1", "token": "TestString",
                               "controller": "FOREIGN"}}, "evaluate sender": {
    "modified_last_name": {"evaluatecontroller": "FOREIGN", "email_address": "TestString", "slack_name": "TestString",
                           "first_name": "TestString", "last_name": "Test String"},
    "modified_first_name": {"evaluatecontroller": "FOREIGN", "email_address": "TestString", "slack_name": "TestString",
                            "first_name": "Test String", "last_name": "TestString"},
    "standard": {"evaluatecontroller": "FOREIGN", "email_address": "TestString", "slack_name": "TestString",
                 "first_name": "TestString", "last_name": "TestString"},
    "missing_last_name": {"evaluatecontroller": "FOREIGN", "email_address": "TestString", "slack_name": "TestString",
                          "first_name": "TestString", "last_name": ""},
    "modified_slack_name": {"evaluatecontroller": "FOREIGN", "email_address": "TestString", "slack_name": "Test String",
                            "first_name": "TestString", "last_name": "TestString"},
    "modified_email_address": {"evaluatecontroller": "FOREIGN", "email_address": "Test String",
                               "slack_name": "TestString", "first_name": "TestString", "last_name": "TestString"},
    "modified_evaluatecontroller": {"evaluatecontroller": "FOREIGN", "email_address": "TestString",
                                    "slack_name": "TestString", "first_name": "TestString", "last_name": "TestString"},
    "missing_slack_name": {"evaluatecontroller": "FOREIGN", "email_address": "TestString", "slack_name": "",
                           "first_name": "TestString", "last_name": "TestString"},
    "missing_evaluatecontroller": {"evaluatecontroller": "", "email_address": "TestString", "slack_name": "TestString",
                                   "first_name": "TestString", "last_name": "TestString"},
    "missing_email_address": {"evaluatecontroller": "FOREIGN", "email_address": "", "slack_name": "TestString",
                              "first_name": "TestString", "last_name": "TestString"},
    "missing_first_name": {"evaluatecontroller": "FOREIGN", "email_address": "TestString", "slack_name": "TestString",
                           "first_name": "", "last_name": "TestString"}}, "evaluate controller": {
    "modified_name": {"scheduled_time": "", "scheduled_type": "1", "expiry_type": "1", "expiry_time": "",
                      "target_controller": "FOREIGN", "targets": "MANY-TO-MANY", "status": "1", "sender": "FOREIGN",
                      "name": "Test String", "description": "Lots of text goes here", "template": "FOREIGN"},
    "modified_targets": {"scheduled_time": "", "scheduled_type": "1", "expiry_type": "1", "expiry_time": "",
                         "target_controller": "FOREIGN", "targets": "MANY-TO-MANY", "status": "1", "sender": "FOREIGN",
                         "name": "TestString", "description": "Lots of text goes here", "template": "FOREIGN"},
    "modified_expiry_type": {"scheduled_time": "", "scheduled_type": "1", "expiry_type": "3", "expiry_time": "",
                             "target_controller": "FOREIGN", "targets": "MANY-TO-MANY", "status": "1",
                             "sender": "FOREIGN", "name": "TestString", "description": "Lots of text goes here",
                             "template": "FOREIGN"},
    "missing_targets": {"scheduled_time": "", "scheduled_type": "1", "expiry_type": "1", "expiry_time": "",
                        "target_controller": "FOREIGN", "targets": "", "status": "1", "sender": "FOREIGN",
                        "name": "TestString", "description": "Lots of text goes here", "template": "FOREIGN"},
    "modified_expiry_time": {"scheduled_time": "", "scheduled_type": "1", "expiry_type": "1", "expiry_time": "",
                             "target_controller": "FOREIGN", "targets": "MANY-TO-MANY", "status": "1",
                             "sender": "FOREIGN", "name": "TestString", "description": "Lots of text goes here",
                             "template": "FOREIGN"},
    "missing_scheduled_type": {"scheduled_time": "", "scheduled_type": "", "expiry_type": "1", "expiry_time": "",
                               "target_controller": "FOREIGN", "targets": "MANY-TO-MANY", "status": "1",
                               "sender": "FOREIGN", "name": "TestString", "description": "Lots of text goes here",
                               "template": "FOREIGN"},
    "missing_scheduled_time": {"scheduled_time": "", "scheduled_type": "1", "expiry_type": "1", "expiry_time": "",
                               "target_controller": "FOREIGN", "targets": "MANY-TO-MANY", "status": "1",
                               "sender": "FOREIGN", "name": "TestString", "description": "Lots of text goes here",
                               "template": "FOREIGN"},
    "modified_status": {"scheduled_time": "", "scheduled_type": "1", "expiry_type": "1", "expiry_time": "",
                        "target_controller": "FOREIGN", "targets": "MANY-TO-MANY", "status": "3", "sender": "FOREIGN",
                        "name": "TestString", "description": "Lots of text goes here", "template": "FOREIGN"},
    "missing_status": {"scheduled_time": "", "scheduled_type": "1", "expiry_type": "1", "expiry_time": "",
                       "target_controller": "FOREIGN", "targets": "MANY-TO-MANY", "status": "", "sender": "FOREIGN",
                       "name": "TestString", "description": "Lots of text goes here", "template": "FOREIGN"},
    "missing_description": {"scheduled_time": "", "scheduled_type": "1", "expiry_type": "1", "expiry_time": "",
                            "target_controller": "FOREIGN", "targets": "MANY-TO-MANY", "status": "1",
                            "sender": "FOREIGN", "name": "TestString", "description": "", "template": "FOREIGN"},
    "modified_description": {"scheduled_time": "", "scheduled_type": "1", "expiry_type": "1", "expiry_time": "",
                             "target_controller": "FOREIGN", "targets": "MANY-TO-MANY", "status": "1",
                             "sender": "FOREIGN", "name": "TestString", "description": "More text but different",
                             "template": "FOREIGN"},
    "missing_expiry_time": {"scheduled_time": "", "scheduled_type": "1", "expiry_type": "1", "expiry_time": "",
                            "target_controller": "FOREIGN", "targets": "MANY-TO-MANY", "status": "1",
                            "sender": "FOREIGN", "name": "TestString", "description": "Lots of text goes here",
                            "template": "FOREIGN"},
    "standard": {"scheduled_time": "", "scheduled_type": "1", "expiry_type": "1", "expiry_time": "",
                 "target_controller": "FOREIGN", "targets": "MANY-TO-MANY", "status": "1", "sender": "FOREIGN",
                 "name": "TestString", "description": "Lots of text goes here", "template": "FOREIGN"},
    "modified_sender": {"scheduled_time": "", "scheduled_type": "1", "expiry_type": "1", "expiry_time": "",
                        "target_controller": "FOREIGN", "targets": "MANY-TO-MANY", "status": "1", "sender": "FOREIGN",
                        "name": "TestString", "description": "Lots of text goes here", "template": "FOREIGN"},
    "missing_sender": {"scheduled_time": "", "scheduled_type": "1", "expiry_type": "1", "expiry_time": "",
                       "target_controller": "FOREIGN", "targets": "MANY-TO-MANY", "status": "1", "sender": "",
                       "name": "TestString", "description": "Lots of text goes here", "template": "FOREIGN"},
    "missing_expiry_type": {"scheduled_time": "", "scheduled_type": "1", "expiry_type": "", "expiry_time": "",
                            "target_controller": "FOREIGN", "targets": "MANY-TO-MANY", "status": "1",
                            "sender": "FOREIGN", "name": "TestString", "description": "Lots of text goes here",
                            "template": "FOREIGN"},
    "missing_template": {"scheduled_time": "", "scheduled_type": "1", "expiry_type": "1", "expiry_time": "",
                         "target_controller": "FOREIGN", "targets": "MANY-TO-MANY", "status": "1", "sender": "FOREIGN",
                         "name": "TestString", "description": "Lots of text goes here", "template": ""},
    "modified_template": {"scheduled_time": "", "scheduled_type": "1", "expiry_type": "1", "expiry_time": "",
                          "target_controller": "FOREIGN", "targets": "MANY-TO-MANY", "status": "1", "sender": "FOREIGN",
                          "name": "TestString", "description": "Lots of text goes here", "template": "FOREIGN"},
    "modified_target_controller": {"scheduled_time": "", "scheduled_type": "1", "expiry_type": "1", "expiry_time": "",
                                   "target_controller": "FOREIGN", "targets": "MANY-TO-MANY", "status": "1",
                                   "sender": "FOREIGN", "name": "TestString", "description": "Lots of text goes here",
                                   "template": "FOREIGN"},
    "missing_target_controller": {"scheduled_time": "", "scheduled_type": "1", "expiry_type": "1", "expiry_time": "",
                                  "target_controller": "", "targets": "MANY-TO-MANY", "status": "1",
                                  "sender": "FOREIGN", "name": "TestString", "description": "Lots of text goes here",
                                  "template": "FOREIGN"},
    "modified_scheduled_type": {"scheduled_time": "", "scheduled_type": "3", "expiry_type": "1", "expiry_time": "",
                                "target_controller": "FOREIGN", "targets": "MANY-TO-MANY", "status": "1",
                                "sender": "FOREIGN", "name": "TestString", "description": "Lots of text goes here",
                                "template": "FOREIGN"},
    "modified_scheduled_time": {"scheduled_time": "", "scheduled_type": "1", "expiry_type": "1", "expiry_time": "",
                                "target_controller": "FOREIGN", "targets": "MANY-TO-MANY", "status": "1",
                                "sender": "FOREIGN", "name": "TestString", "description": "Lots of text goes here",
                                "template": "FOREIGN"},
    "missing_name": {"scheduled_time": "", "scheduled_type": "1", "expiry_type": "1", "expiry_time": "",
                     "target_controller": "FOREIGN", "targets": "MANY-TO-MANY", "status": "1", "sender": "FOREIGN",
                     "name": "", "description": "Lots of text goes here", "template": "FOREIGN"}},
          "evaluate result": {"modified_result": {"result": "3", "target_profile": "FOREIGN"},
                              "missing_target_profile": {"result": "1", "target_profile": ""},
                              "standard": {"result": "1", "target_profile": "FOREIGN"},
                              "modified_target_profile": {"result": "1", "target_profile": "FOREIGN"},
                              "missing_result": {"result": "", "target_profile": "FOREIGN"}},
          "evaluatecontroller-person relationship": {
              "modified_person": {"person": "FOREIGN", "evaluatecontroller": "FOREIGN"},
              "missing_person": {"person": "", "evaluatecontroller": "FOREIGN"},
              "missing_evaluatecontroller": {"person": "FOREIGN", "evaluatecontroller": ""},
              "standard": {"person": "FOREIGN", "evaluatecontroller": "FOREIGN"},
              "modified_evaluatecontroller": {"person": "FOREIGN", "evaluatecontroller": "FOREIGN"}}}}
