# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestDataFieldReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(max_length=100, unique=True)),
                ('standard_value', models.CharField(max_length=1000, null=True)),
                ('modified_value', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
