# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organize', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluateController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('scheduled_type', models.IntegerField(choices=[(0, 'Now'), (1, 'Scheduled')], default=0)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('expiry_type', models.IntegerField(choices=[(0, 'Day'), (1, 'Week'), (2, 'Month')], default=1)),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Pending'), (2, 'Processed'), (3, 'Active'), (4, 'Expired')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluateResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('result', models.IntegerField(choices=[(0, 'Fail'), (1, 'Pass')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluateSender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email_address', models.EmailField(max_length=254)),
                ('slack_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluateTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('template_type', models.IntegerField(choices=[(0, 'Email'), (1, 'Slack')], default=0)),
                ('email_subject', models.CharField(blank=True, max_length=128, null=True)),
                ('email_body', models.TextField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluateTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=128)),
                ('delivery_status', models.IntegerField(choices=[(0, 'Pending'), (2, 'Sent'), (3, 'Error')], default=0)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_controller', to='evaluate.EvaluateController')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organize.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='evaluateresult',
            name='target_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluate.EvaluateTest'),
        ),
        migrations.AddField(
            model_name='evaluatecontroller',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluate.EvaluateSender'),
        ),
        migrations.AddField(
            model_name='evaluatecontroller',
            name='targets',
            field=models.ManyToManyField(to='organize.Person'),
        ),
        migrations.AddField(
            model_name='evaluatecontroller',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluate.EvaluateTemplate'),
        ),
    ]
