# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0002_evaluatesender_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluatetemplate',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
