{"data": {"achievement": {
    "modified_achievement": {"icon_url": "TestString", "score": "1", "achievement": "FOREIGN", "name": "TestString",
                             "description": "Lots of text goes here"},
    "modified_description": {"icon_url": "TestString", "score": "1", "achievement": "FOREIGN", "name": "TestString",
                             "description": "More text but different"},
    "missing_icon_url": {"icon_url": "", "score": "1", "achievement": "FOREIGN", "name": "TestString",
                         "description": "Lots of text goes here"},
    "missing_score": {"icon_url": "TestString", "score": "", "achievement": "FOREIGN", "name": "TestString",
                      "description": "Lots of text goes here"},
    "standard": {"icon_url": "TestString", "score": "1", "achievement": "FOREIGN", "name": "TestString",
                 "description": "Lots of text goes here"},
    "modified_icon_url": {"icon_url": "Test String", "score": "1", "achievement": "FOREIGN", "name": "TestString",
                          "description": "Lots of text goes here"},
    "modified_score": {"icon_url": "TestString", "score": "3", "achievement": "FOREIGN", "name": "TestString",
                       "description": "Lots of text goes here"},
    "modified_name": {"icon_url": "TestString", "score": "1", "achievement": "FOREIGN", "name": "Test String",
                      "description": "Lots of text goes here"},
    "missing_achievement": {"icon_url": "TestString", "score": "1", "achievement": "", "name": "TestString",
                            "description": "Lots of text goes here"},
    "missing_description": {"icon_url": "TestString", "score": "1", "achievement": "FOREIGN", "name": "TestString",
                            "description": ""},
    "missing_name": {"icon_url": "TestString", "score": "1", "achievement": "FOREIGN", "name": "",
                     "description": "Lots of text goes here"}}}}
