# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suspicious',
            old_name='url',
            new_name='suspicious_url',
        ),
    ]
