# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integration_office365', '0001_initial'),
        ('gather_abstract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office365GatherHistory',
            fields=[
                ('gatherhistory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gather_abstract.GatherHistory')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office365_integration_history', to='integration_office365.Office365IntegrationAdapter')),
            ],
            options={
                'abstract': False,
            },
            bases=('gather_abstract.gatherhistory',),
        ),
    ]
