# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integration_office365', '0001_initial'),
        ('gather_office365', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office365gatherhistory',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office365_integration_history', to='integration_office365.Office365IntegrationAdapter'),
        ),
    ]
