# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 06:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='office365_identity_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Office365 Data'),
        ),
        migrations.AlterField(
            model_name='groupidentifier',
            name='identifier_type',
            field=models.CharField(choices=[('EMAIL', 'Email Address'), ('SKYPE', 'Skype ID'), ('IPADD', 'IP Address'), ('UNAME', 'Username'), ('TWITTER', 'Twitter ID'), ('NAME', 'Other name'), ('GOOGLE_ID', 'Google ID'), ('OFFICE_ID', 'Office ID'), ('GUID', 'Guid'), ('SID', 'Sid')], default='EMAIL', max_length=10, verbose_name='Identifier Type'),
        ),
        migrations.AlterField(
            model_name='personidentifier',
            name='identifier_type',
            field=models.CharField(choices=[('EMAIL', 'Email Address'), ('SKYPE', 'Skype ID'), ('IPADD', 'IP Address'), ('UNAME', 'Username'), ('TWITTER', 'Twitter ID'), ('NAME', 'Other name'), ('GOOGLE_ID', 'Google ID'), ('OFFICE_ID', 'Office ID'), ('GUID', 'Guid'), ('SID', 'Sid')], default='EMAIL', max_length=10, verbose_name='Identifier Type'),
        ),
    ]
