# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 22:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organize', '0002_personidentifierreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('reason_type', models.IntegerField(choices=[(0, 'Remove me')], default=0)),
                ('priority_type', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High'), (3, 'Critical')], default=0)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organize.Group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='personidentifierreport',
            name='reason_type',
            field=models.IntegerField(choices=[(0, 'Personal account'), (1, 'Incorrect information'), (2, 'Incorrect owner'), (3, 'Outdated')], default=0),
        ),
    ]
