# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0002_auto_20160207_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='google_group_data',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='ldap_group_data',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='google_identity_data',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Google Data'),
        ),
        migrations.AlterField(
            model_name='person',
            name='ldap_identity_data',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='LDAP Data'),
        ),
        migrations.AlterField(
            model_name='person',
            name='office365_identity_data',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Office365 Data'),
        ),
    ]
