# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_abstract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationadapter',
            name='credential',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
