# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integration_abstract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office365AuthorizationStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Office365IntegrationAdapter',
            fields=[
                ('integrationadapter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='integration_abstract.IntegrationAdapter')),
                ('domain', models.URLField(unique=True)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
            bases=('integration_abstract.integrationadapter',),
        ),
    ]
